"""
Pydantic v2 schemas for the AI Business Model Canvas feature.
"""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class BMCBlockData(BaseModel):
    """Structured container for a single canvas block."""
    items: List[str] = Field(default_factory=list, description="Concise bullet points for this block")
    generated_by_ai: bool = Field(default=True, description="True if generated by AI, False if fully custom")
    modified_by_founder: bool = Field(default=False, description="True if edited by the founder")
    last_updated: Optional[str] = Field(default=None, description="ISO timestamp string of last modification")
    risk_notes: Optional[str] = Field(default=None, description="Risk callouts attached during Pivot-Aware mode")


class BMCBlocksRaw(BaseModel):
    """Raw Gemini response schema for all 9 blocks (list of strings per block)."""
    customer_segments: List[str] = Field(..., description="Target customer segments")
    value_propositions: List[str] = Field(..., description="Core value propositions addressing pain points")
    channels: List[str] = Field(..., description="Sales and distribution channels")
    customer_relationships: List[str] = Field(..., description="Relationship types and onboarding models")
    revenue_streams: List[str] = Field(..., description="Monetization mechanisms and revenue origins")
    key_resources: List[str] = Field(..., description="Critical physical, intellectual, human, financial resources")
    key_activities: List[str] = Field(..., description="Primary operational activities required")
    key_partnerships: List[str] = Field(..., description="Strategic partners, suppliers, alliances")
    cost_structure: List[str] = Field(..., description="Major cost drivers reflecting activities, resources, channels")


class AuditConflict(BaseModel):
    """Structured audit conflict issue."""
    severity: str = Field(..., description="'warning', 'error', or 'info'")
    blocks: List[str] = Field(..., description="List of block names involved in conflict")
    title: str = Field(..., description="Short title of conflict")
    description: str = Field(..., description="Detailed explanation of contradiction")
    recommendation: str = Field(..., description="Actionable recommendation for founder")


class BMCAuditReport(BaseModel):
    """Structured Red Pen Audit output."""
    health_score: int = Field(..., ge=0, le=100, description="Overall BMC health score (0-100)")
    conflicts: List[AuditConflict] = Field(default_factory=list, description="List of detected logical contradictions")


class BMCVersionResponse(BaseModel):
    """Full API response for a single BMC version."""
    id: int
    startup_id: int
    version: int
    canvas_data: Dict[str, Any]
    audit_data: Dict[str, Any]
    validation_score: Optional[float] = None
    generation_mode: str
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class BMCVersionHistoryItem(BaseModel):
    """Lightweight history item for version list."""
    id: int
    version: int
    validation_score: Optional[float] = None
    generation_mode: str
    created_at: datetime

    class Config:
        from_attributes = True


class BlockUpdatePayload(BaseModel):
    """Payload when founder updates a single block manually."""
    items: List[str] = Field(..., min_items=1, description="Updated bullet points for the block")


class BlockRegeneratePayload(BaseModel):
    """Payload when requesting AI regeneration of a single block."""
    custom_instructions: Optional[str] = Field(default=None, description="Optional extra instructions from founder")
