"""create_startups_table

Revision ID: 47a2ce2528ab
Revises: 9b7f267ba6e9
Create Date: 2026-08-10 21:57:57.821655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a2ce2528ab'
down_revision: Union[str, Sequence[str], None] = '9b7f267ba6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('target_market', sa.String(length=200), nullable=True),
    sa.Column('stage', sa.Enum('IDEA', 'PROTOTYPE', 'MVP', 'EARLY_TRACTION', 'GROWTH', name='startupstage'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='startupstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('founder_id', name='uq_startups_founder_id')
    )
    op.create_index(op.f('ix_startups_id'), 'startups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startups_id'), table_name='startups')
    op.drop_table('startups')
    # ### end Alembic commands ###
