"""create_idea_validations_table

Revision ID: 793350f693a1
Revises: 47a2ce2528ab
Create Date: 2026-08-11 22:18:30.259554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '793350f693a1'
down_revision: Union[str, Sequence[str], None] = '47a2ce2528ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lofa', sa.Text(), nullable=False),
    sa.Column('agent_vc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_buyer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_competitor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('problem_score', sa.Integer(), nullable=False),
    sa.Column('buyer_score', sa.Integer(), nullable=False),
    sa.Column('market_score', sa.Integer(), nullable=False),
    sa.Column('moat_score', sa.Integer(), nullable=False),
    sa.Column('feasibility_score', sa.Integer(), nullable=False),
    sa.Column('weighted_base_score', sa.Float(), nullable=False),
    sa.Column('final_validation_score', sa.Float(), nullable=False),
    sa.Column('vetoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('penalty_multiplier', sa.Float(), nullable=False),
    sa.Column('score_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_assessment', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mom_test_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kill_threshold', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id', 'version', name='uq_validation_startup_version')
    )
    op.create_index(op.f('ix_idea_validations_id'), 'idea_validations', ['id'], unique=False)
    op.create_index(op.f('ix_idea_validations_startup_id'), 'idea_validations', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_validations_startup_id'), table_name='idea_validations')
    op.drop_index(op.f('ix_idea_validations_id'), table_name='idea_validations')
    op.drop_table('idea_validations')
    # ### end Alembic commands ###
